name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint Frontend & Backend
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # LINT FRONTEND
      - name: Install & lint frontend
        working-directory: frontend
        run: |
          npm ci
          npm install --no-save globals eslint-plugin-react @eslint/js
          npx eslint . --ext .js,.jsx,.ts,.tsx

      # LINT BACKEND
      - name: Install & lint backend
        working-directory: backend
        run: |
          npm ci
          npm install --no-save globals eslint-plugin-react @eslint/js
          npx eslint . --ext .js,.jsx,.ts,.tsx

  test-backend:
    name: Run Backend Tests & Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      # TEST WITH COVERAGE
      - name: Run backend tests with coverage
        working-directory: backend
        run: npm test -- --coverage

