name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint Frontend & Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & lint frontend
        working-directory: frontend
        run: |
          npm ci
          npm install --no-save globals eslint-plugin-react @eslint/js
          npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Install & lint backend
        working-directory: backend
        run: |
          npm ci
          npm install --no-save globals eslint-plugin-react @eslint/js
          npx eslint . --ext .js,.jsx,.ts,.tsx

  test-backend:
    name: Run Backend Tests & Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Install dependencies
        run: |
          cd backend && npm ci
          cd ../frontend && npm ci

      - name: Start backend server
        working-directory: backend
        run: npm start &

      - name: Start frontend server
        working-directory: frontend
        run: npm start &

      - name: Run backend tests with coverage
        working-directory: backend
        run: npm test -- --coverage


